### ISSUE TITLE
Errors in downloaded CSV files: shifted columns

### ISSUE THREAD

**Issue by LauraSchweibold** [iobis/haedat-issues#15]
Sometimes a shift appears in data, so the rest of the concerned line is shifted. Commas used in written comments must be linked.

Here is an example with data from the US, 
below is the comment displayed in HAEDAT:
<img width="344" alt="2 1 shifts" src="https://user-images.githubusercontent.com/32324272/30906931-96b082a8-a379-11e7-9488-fe6fd96fc412.png">
and here is the corresponding data in Excel (line 190), the text shifted from the first comma. This even induce a shift in the next line (191).
<img width="869" alt="2 2 shifts" src="https://user-images.githubusercontent.com/32324272/30906986-c2c3d26e-a379-11e7-8caf-dd3a5bd12a9b.png">

Another example with Canadian data,
comment displayed in HAEDAT:
<img width="546" alt="2 4 shifts" src="https://user-images.githubusercontent.com/32324272/30907130-31111e52-a37a-11e7-894e-2fcbc23ae198.png">
and correspondind data in Excel, each comma in the text induced a shift:
<img width="910" alt="2 3 shifts" src="https://user-images.githubusercontent.com/32324272/30907249-71360b32-a37a-11e7-87c5-ce9bbbbf3377.png">

**Comment by pieterprovoost** [comment]
No problem in Excel for Mac, but the issue seems to be related to line breaks (`\r\n` instead if `\n`) in the `effectsComments` field.

@LauraSchweibold Can you please try if the problem with this particular record is still present in the attached CSV file?

[haedat_search.csv.zip](https://github.com/iobis/haedat-issues/files/1337061/haedat_search.csv.zip)

**Comment by pieterprovoost** [comment]
Fixed https://github.com/iobis/haedat/commit/f174f2b607dfb339c630e295eb6f5ea71fceaa5e
